language: java
jdk:
  - openjdk17

# Git Push할 Branch
branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'


# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jiyoon778@gmail.com

script: "./gradlew clean build"

before_deploy:
  - zip -r daydei-test.zip *
  - mkdir -p deploy
  - mv daydei-test.zip deploy/daydei-test.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: daydei-actions-s3-bucket # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    on:
      repo: trueyoon/DAYdeiBackRepo #Github 주소
      branch: develop
