language: java
jdk:
  - openjdk17

# Git Push할 Branch
branches:
  only:
    - main
 # 외쳐 갓 도경
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

jobs:
  include:
    - name: make application.properties
      script: touch ./src/main/resources/application.properties
    - name: deliver application.properties
      script: echo "${APPLICATION_DEV}" > ./src/main/resources/application.properties

script: "./gradlew clean build"

before_deploy:
  - zip -r daydei-test.zip *
  - mkdir -p deploy
  - mv daydei-test.zip deploy/daydei-test.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: daydei-actions-s3-bucket # 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    on:
      repo: trueyoon/DaydeiTest #Github 주소
      branch: develop

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: daydei-actions-s3-bucket # S3 버킷
    key: daydei-test.zip # S3 버킷에 저장된 jaewon-study.zip 파일을 EC2로 배포
    bundle_type: zip
    application: my-codedeploy-app2 # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: my-ec2-group2 # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: trueyoon/DaydeiTest
      branch: main



# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - jiyoon778@gmail.com
